// Generated by Wrangler by running `wrangler types`

interface Env {
	KV: KVNamespace;
	CITY_API_BASE_URL: "https://secure.toronto.ca/cc_sr_v1/data/edc_eventcal_APR?limit=500";
	R2_BASE_URL: "https://r2.eventto.ca/";
	API_TOKEN: string;
	CLOUDFLARE_ACCOUNT_ID: string;
	CLOUDFLARE_AI_API_TOKEN: string;
	R2: R2Bucket;
	DB: D1Database;
	AI: Ai;
}
