// Generated by Wrangler by running `wrangler types`

interface Env {
	CITY_API_BASE_URL: "https://secure.toronto.ca/cc_sr_v1/data/edc_eventcal_APR?limit=500";
	API_TOKEN: string;
	ACCOUNT_ID: string;
	CLOUDFLARE_IMAGE_API_TOKEN: string;
	bucket: R2Bucket;
	DB: D1Database;
}
