// Generated by Wrangler by running `wrangler types`

interface Env {
	CITY_API_BASE_URL: "https://secure.toronto.ca/cc_sr_v1/data/edc_eventcal_APR?limit=500";
	CITY_API_SECURE_URL: "https://secure.toronto.ca";
	DB: D1Database;
}
